packages:
  # specify a package in a direct subdir of the root
  - "backend"
  - "frontend"
  # exclude packages that are inside test directories
  - "!**/test/**"
allowBuilds:
  '@scarf/scarf': set this to true or false
  unrs-resolver: true
