import type { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateOrgUnits20260926000000 implements MigrationInterface {
  name = 'CreateOrgUnits20260926000000';

  async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE "org_units" (
        "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "parent_id" integer,
        "type" varchar(50) NOT NULL,
        "name" varchar(150) NOT NULL,
        CONSTRAINT "FK_org_units_parent_id"
          FOREIGN KEY ("parent_id")
          REFERENCES "org_units"("id")
          ON DELETE RESTRICT
      )
    `);

    await queryRunner.query(
      'CREATE INDEX "IDX_org_units_parent_id" ON "org_units" ("parent_id")',
    );
  }

  async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('DROP INDEX "IDX_org_units_parent_id"');
    await queryRunner.query('DROP TABLE "org_units"');
  }
}
