import type { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateUsers20260927000000 implements MigrationInterface {
  name = 'CreateUsers20260927000000';

  async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE "users" (
        "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "username" varchar(40) NOT NULL,
        "user_id" varchar(255) NOT NULL,
        CONSTRAINT "UQ_users_username" UNIQUE ("username")
      )
    `);
  }

  async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('DROP TABLE "users"');
  }
}
